### ISSUE TITLE
Are the syntactic dependencies only for RVWMO?

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-zicond#17]
The latest version of the spec says:
`For the purposes of RVWMO, _rd_ syntactically depends on both _rs1_ and _rs2_.`
Do we want to limit this to RVWMO? It seems like this should say:
`For the purposes of the memory model, _rd_ syntactically depends on both _rs1_ and _rs2_.`

**Comment by ptomsich** [comment]
@aswaterman Should we extend this to generically cover "the memory model"?

**Comment by aswaterman** [comment]
Technically, I think this variant is more correct: the term "syntactic dependency" only makes sense in the context of RVWMO (since that's where it's defined).  And Ztso implementations are RVWMO-compliant, so this statement necessarily applies to Ztso, too.

To avoid confusion without creating a different ambiguity, I'll just delete the dependent clause.
